### ISSUE TITLE
Norvrandt - The Tempest fails to build

### ISSUE THREAD

**Issue by mwyschan** [awgil/ffxiv_navmesh#13]
```
20:42:48.188 | ERR | [vnavmesh] Failed to build navmesh: System.AggregateException: One or more errors occurred. ('8192' cannot be greater than 8191.)
	 ---> System.ArgumentException: '8192' cannot be greater than 8191.
	   at System.Math.ThrowMinMaxException[T](T min, T max)
	   at Navmesh.NavmeshRasterizer.RasterizeMesh(Mesh mesh, MeshInstance instance, Int32& minimalY) in /home/runner/work/ffxiv_navmesh/ffxiv_navmesh/vnavmesh/NavmeshRasterizer.cs:line 269
	   at Navmesh.NavmeshRasterizer.Rasterize(SceneExtractor geom, MeshType types, Boolean perMeshInteriors, Boolean solidBelowNonManifold) in /home/runner/work/ffxiv_navmesh/ffxiv_navmesh/vnavmesh/NavmeshRasterizer.cs:line 147
	   at Navmesh.NavmeshBuilder.BuildTile(Int32 x, Int32 z) in /home/runner/work/ffxiv_navmesh/ffxiv_navmesh/vnavmesh/NavmeshBuilder.cs:line 106
	   at Navmesh.NavmeshManager.BuildNavmesh(SceneDefinition scene, Boolean flyable, String cacheKey, Boolean allowLoadFromCache) in /home/runner/work/ffxiv_navmesh/ffxiv_navmesh/vnavmesh/NavmeshManager.cs:line 240
	   at Navmesh.NavmeshManager.<>c__DisplayClass31_0.<Reload>b__0() in /home/runner/work/ffxiv_navmesh/ffxiv_navmesh/vnavmesh/NavmeshManager.cs:line 129
	   at System.Threading.Tasks.Task`1.InnerInvoke()
	   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
	   --- End of inner exception stack trace ---
	   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
	   at Navmesh.NavmeshManager.Update() in /home/runner/work/ffxiv_navmesh/ffxiv_navmesh/vnavmesh/NavmeshManager.cs:line 65
```

**Comment by RikaKagurasaka** [comment]
same problem here

**Comment by awgil** [comment]
Fixed.
